# Unfollower - GitHub Actions auto-unfollow tool
# Copyright (C) 2026  mwakidenis
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
name: Unfollow Non-Followers

on:
  schedule:
    # Runs every 5 days (days 1, 6, 11, 16, 21, 26, 31 of each month)
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  unfollow_non_followers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Unfollow users who don't follow back
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python main.py ${{ secrets.GH_TOKEN }}
        shell: bash -l {0}
